# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.0.1
maven_group=org.cneko
archives_name=LEDIt
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.16.14
fabric_api_version=0.116.14+1.21.1
neoforge_version=21.1.241
# Cloth Config and ModMenu
cloth_config_version=15.0.127
modmenu_version=11.0.3
